Handle powers of units and expand macros better
ISISComputingGroup/EPICS-DbUnitChecker pull request #6
Opened 2017-04-14 12:53 UTC by FreddieAkeroyd

Should now handle mm^2 etc.

2017-04-18 09:57 UTC, AdrianPotter requested changes

2017-04-18 09:57 UTC, AdrianPotter commented on db_checker.py
> +                if not (re.match(allowed_units_prefixes, u[0]) and u[1:] in allowed_units):
Why are we using regex match to check for character matches? Surely using a set like allowed units would be more consistent and Pythonic.

2017-04-18 10:17 UTC, ThomasLohnert requested changes
Happened to review this at the same time as Adrian - added some additional comments in the code.

2017-04-18 10:17 UTC, ThomasLohnert commented on db_checker.py
> +                 'interrupt', 'K', 'L', 'm', 'min', 'minute', 'ohm', 'Oersted', '%', 'photon', 'pixel', 'radian', 's','torr', 'step', 'T', 'V', 'cm', 'Pa'}
Style: should have a line break after 's',

2017-04-18 10:17 UTC, ThomasLohnert commented on db_checker.py
> +allowed_units_prefixes = r'T|G|M|k|m|u|n|p|f';
Style: remove trailing semicolon

2017-04-18 10:17 UTC, ThomasLohnert commented on db_checker.py
> +            u = re.sub(r'\^[-]?\d', '', u)
This does not check whether the power symbol is actually in the right place and passes e.g. ^2MHz, M^2H^2z etc. Also allows endlessly stacking power units e.g. MHz^2^-3^2^3, which although technically a valid unit, I'm not sure whether it's a sensible thing to allow?

2017-04-18 15:07 UTC, FreddieAkeroyd commented on db_checker.py
> +                if not (re.match(allowed_units_prefixes, u[0]) and u[1:] in allowed_units):
A good point, given I refactored the string into a constant I should have gone further and done that

2017-04-18 15:18 UTC, FreddieAkeroyd commented on db_checker.py
> +            u = re.sub(r'\^[-]?\d', '', u)
I can add a count to sub to make it do only one replace, then ^2^3 should fail. I think I can add a [A-Za-z]+ to the satisfy the other matter. In the future, maybe we should be using https://pypi.python.org/pypi/cf_units ?

2017-04-18 15:23 UTC, FreddieAkeroyd commented on db_checker.py
> +allowed_units_prefixes = r'T|G|M|k|m|u|n|p|f';
You can tell I'm a C++ programmer at heart :-D

2017-04-18 15:50 UTC, ThomasLohnert commented on db_checker.py
> +            u = re.sub(r'\^[-]?\d', '', u)
The changes cover most of these cases now, but still pass if there is just one power modifier somewhere in the middle of the unit (as long as there's at least one letter that comes before it). Adding an "end of string" character `$` to the end of the regex should do the trick though (assuming that the power modifier will always be the last part of the unit description)

2017-04-18 20:54 UTC, FreddieAkeroyd commented on db_checker.py
> +            u = re.sub(r'\^[-]?\d', '', u)
Good idea, and good testing

2017-04-18 20:58 UTC, FreddieAkeroyd commented on db_checker.py
> +            u = re.sub(r'\^[-]?\d', '', u)
I'll assume we don't need to handle fractional unit powers ( 1.5 or 3/2) for now!

2017-04-19 08:08 UTC, ThomasLohnert approved these changes

2017-04-30 21:20 UTC, FreddieAkeroyd commented
@AdrianPotter is there anything still pending on this?

2017-05-04 11:58 UTC, DominicOram commented
Minor issues: 
* Now that cm is a valid unit all the prefixes are also valid e.g. "mcm", "kcm", "Tcm" etc.
* In some cases brackets cause a string index out of range exception to be thrown. e.g. "K/(m s)"  
* More of a question, should we allow units such as "1/m"? The program currently does not

It would also be good if we could add unit tests to the checker, which I know might be tricky as it is itself a test suite but it will help avoid this issue coming up again?

2017-05-09 13:43 UTC, FreddieAkeroyd commented
I wonder if we dhould just use something like https://pypi.python.org/pypi/cf_units or https://pypi.python.org/pypi/cfunits/1.0.1

2017-05-17 08:30 UTC, AdrianPotter approved these changes

2017-06-09 16:40 UTC, AdrianPotter commented
- I've set up a `db` file to specifically test units. This can be run using `test_checker.bat`
- I've improved and simplified the unit testing logic. It also caught several failing cases in the new tests. This includes Dom's points
- I haven't allowed 1/m for the time being
- I looked at using one of the libraries Freddie suggested but I had trouble getting them using `pip install` so decided they were more trouble than they were worth.

2017-06-22 10:31 UTC, merged